filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/application.log

output.kafka:
  hosts: [ "kafka:9092" ]
  topic: "OMG"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  codec.json:
    pretty: false